#!/bin/bash
# Undrip.sh — the RESET button for Dripfeed (auto-generated by Dripfeed.sh).
# Restores every scheduled game to its normal folder, deletes all Dripfeed folders,
# shortcuts, and settings (keeping only Scripts/Dripfeed.sh), then reboots so the menu
# comes back clean. Re-run Dripfeed.sh afterwards for a clean reinstall or a fresh
# schedule. Press ANY button to confirm; doing nothing cancels safely.

DRIPFEED_ROOT="${DRIPFEED_ROOT:-/media/fat}"
HELP="$DRIPFEED_ROOT/Scripts/.dripfeed"
export DRIPFEED_INTERACTIVE=1
[ -f "$HELP/dripfeed-common.sh" ] && . "$HELP/dripfeed-common.sh"

clear 2>/dev/null || printf '\033[2J\033[H'
echo
echo "  ================  DRIPFEED  -  UNDRIP (RESET)  ================"
echo
echo "  Restores ALL scheduled games to their folders, deletes every"
echo "  Dripfeed folder / shortcut / setting (keeps Scripts/Dripfeed.sh),"
echo "  then reboots. Your ROMs and saves are NOT touched."
echo
if type df_confirm_any >/dev/null 2>&1; then
  df_ui_begin; trap 'df_ui_end' EXIT
  echo "  Press ANY button now to UNDRIP - or do nothing to cancel."
  if df_confirm_any 10; then
    echo; echo "  Resetting..."
    "$HELP/dripfeed-engine.sh" --undrip
    df_menu_countdown 5 "Rebooting" >/dev/null
    sync; reboot 2>/dev/null || true
  else
    echo; echo "  Cancelled - nothing changed."; sleep 2
  fi
else
  echo "  (helpers missing) - nothing to do."; sleep 3
fi
exit 0
